### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by spereverde** [collective/collective.explicitacquisition#2]

**Comment by spereverde** [comment]
- all migration to python 3 done as far as i can see
- tests are failing, but checked on master branch with python 2.7 and they were already failing, created issue for this: #3

**Comment by jensens** [comment]
troove classifiers are in need of some enhancement

**Comment by jensens** [comment]
todo here:

- [ ] add changelog entry
- [ ]change troove classifiers
- [ ] create pull request of `python3` branch
- [ ] fix tests

**Comment by jensens** [comment]
except test-fixes all done
